package trinity:api;

interface kv {
    variant kv-error {
        internal(string)
    }

    set: func(key: list<u8>, value: list<u8>) -> result<_, kv-error>;
    get: func(key: list<u8>) -> result<option<list<u8>>, kv-error>;
    remove: func(key: list<u8>) -> result<_, kv-error>;
}

world kv-world {
    import kv;
}
