package trinity:api;

interface log {
    trace: func(s: string);
    debug: func(s: string);
    info: func(s: string);
    warn: func(s: string);
    error: func(s: string);
}

world log-world {
    import log;
}
