package trinity:api;

interface sync-request {
    enum request-verb {
        get, put, delete, post
    }

    record request-header {
        key: string,
        value: string,
    }

    record request {
        verb: request-verb,
        url: string,
        headers: list<request-header>,
        body: option<string>
    }

    enum response-status {
        success, error
    }

    record response {
        status: response-status,
        body: option<string>,
    }

    /// An error happened while trying to run a request.
    variant run-request-error {
        /// The builder couldn't be created.
        builder(string),
        /// The request couldn't be executed.
        execute(string)
    }

    run-request: func(req: request) -> result<response, run-request-error>;
}

world sync-request-world {
    import sync-request;
}
