interface sync-request {
    enum request-verb {
        get, put, delete, post
    }

    record request-header {
        key: string,
        value: string,
    }

    record request {
        verb: request-verb,
        url: string,
        headers: list<request-header>,
        body: option<string>
    }

    enum response-status {
        success, error
    }

    record response {
        status: response-status,
        body: option<string>,
    }

    run-request: func(req: request) -> result<response>
}

default world sync-request-world {
    import sync-request: self.sync-request
}
