interface messaging {
    record message {
        content: string,
        to: string
    }

    type reaction = string

    variant action {
        respond(message),
        react(reaction)
    }

    init: func()
    help: func(topic: option<string>) -> string
    admin: func(cmd: string, author-id: string, room: string) -> list<action>
    on-msg: func(content: string, author-id: string, author-name: string, room: string) -> list<action>
}

default world trinity-module {
    export messaging: self.messaging
}
